//! Custom resources for Provisioned Throughput (docs/08 §2).
//!
//! | Kind | Scope | Written by | Read by |
//! |------|-------|------------|---------|
//! | [`PerformanceProfile`] | cluster | Calibration Service | capacity controller |
//! | [`ModelPool`] | namespaced | platform team / GitOps | capacity controller |
//! | [`PoolAllocation`] | namespaced | global Capacity Planner | capacity controller, router |
//! | [`CapacityReservation`] | namespaced | Entitlement Distributor (read-only mirror) | audit, controllers |

pub mod allocation;
pub mod condition;
pub mod pool;
pub mod profile;
pub mod reservation;

use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;
use kube::CustomResourceExt;

pub use allocation::{PoolAllocation, PoolAllocationSpec};
pub use condition::Condition;
pub use pool::{ModelPool, ModelPoolSpec, ModelPoolStatus};
pub use profile::{PerformanceProfile, PerformanceProfileSpec};
pub use reservation::{CapacityReservation, CapacityReservationSpec};

/// API group for all PT resources.
pub const GROUP: &str = "pt.example.com";

/// Label keys the controller puts on serving pods, used by PDB selectors.
pub mod labels {
    pub const POOL: &str = "pt.example.com/pool";
    pub const ROLE: &str = "pt.example.com/role";
    pub const MANAGED_BY: &str = "app.kubernetes.io/managed-by";
    pub const MANAGER: &str = "pt-operator";
}

/// Every CRD, in install order.
pub fn all_crds() -> Vec<CustomResourceDefinition> {
    vec![
        PerformanceProfile::crd(),
        ModelPool::crd(),
        PoolAllocation::crd(),
        CapacityReservation::crd(),
    ]
}

/// File name under `deploy/crds/` for a CRD.
pub fn crd_file_name(crd: &CustomResourceDefinition) -> String {
    format!("{}.yaml", crd.spec.names.plural)
}

/// YAML for one CRD, with a header marking it as generated.
pub fn crd_yaml(crd: &CustomResourceDefinition) -> anyhow::Result<String> {
    Ok(format!(
        "# Generated by `cargo run -p pt-crds --bin crdgen`. Do not edit.\n{}",
        serde_yaml::to_string(crd)?
    ))
}
